rules:
  - type: RULE-SET
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
    policy: REJECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockclash.list
    policy: REJECT
  - type: RULE-SET
    url: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
    policy: REJECT
  - type: GEOIP
    country: CN
    policy: DIRECT
  - type: GEOIP
    country: PRIVATE
    policy: DIRECT
  - type: FINAL
    policy: PROXY
